language: cpp
script:
  - cmake -H. -Bbuild -G"Unix Makefiles"
  - cmake --build build --config Release
compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libstdc++-7-dev
matrix:
  include:
    - os: linux
    - os: windows
      before_script:
        - choco install make 
        - export CXX=clang-cl
        - export CC=clang-cl
