language: cpp
matrix:
  include:
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libglm-dev
        - libxrandr-dev
        - libxinerama-dev
        - libxcursor-dev
        - libxi-dev
        - libstdc++-7-dev
    before_script:
    - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release  
    script:
    - cmake --build build
  - os: windows
    before_script:
    - cmake -H. -Bbuild -G"Visual Studio 15 2017"
    script:
    - msbuild /P:Configuration=Release build\ALL_BUILD.vcxproj /std:c++17
