language: cpp
before_script:
  - cmake -H. -Bbuild
script:
  - cmake --build build --config Release
matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libglm-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libstdc++-7-dev
    - os: windows