language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libglm-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libstdc++-7-dev
      before_script:
        - cmake -H. -Bbuild
      script:
        - cmake --build build --config Release
    - os: windows
      before_script:
        - nuget install glm
        - cmake -H. -Bbuild
      script:
        - cmake --build build --config Release
