os:
  - linux
  - windows
language: cpp
before_script:
  - cmake --help
  - cmake -H. -Bbuild -G"Unix Makefiles"
script:
  - cmake --build build --config Release
compiler: clang
addons:
  choco:
    packages:
      - make
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libstdc++-7-dev
