#include <Blob/SDL2/Controls.hpp>
#include <SDL2/SDL.h>
#include <SDL2/SDL_keycode.h>

namespace Blob::SDL2 {

const int Keys::UNKNOWN = SDLK_UNKNOWN;
const int Keys::SPACE = SDLK_SPACE;
const int Keys::APOSTROPHE = SDLK_QUOTE;
const int Keys::COMMA = SDLK_COMMA;
const int Keys::MINUS = SDLK_MINUS;
const int Keys::PERIOD = SDLK_PERIOD;
const int Keys::SLASH = SDLK_SLASH;
const int Keys::Zero = SDLK_0;
const int Keys::One = SDLK_1;
const int Keys::Two = SDLK_2;
const int Keys::Three = SDLK_3;
const int Keys::Four = SDLK_4;
const int Keys::Five = SDLK_5;
const int Keys::Six = SDLK_6;
const int Keys::Seven = SDLK_7;
const int Keys::Eight = SDLK_8;
const int Keys::Nine = SDLK_9;
const int Keys::SEMICOLON = SDLK_SEMICOLON;
const int Keys::EQUAL = SDLK_EQUALS;
const int Keys::A = SDLK_a;
const int Keys::B = SDLK_b;
const int Keys::C = SDLK_c;
const int Keys::D = SDLK_d;
const int Keys::E = SDLK_e;
const int Keys::F = SDLK_f;
const int Keys::G = SDLK_g;
const int Keys::H = SDLK_h;
const int Keys::I = SDLK_i;
const int Keys::J = SDLK_j;
const int Keys::K = SDLK_k;
const int Keys::L = SDLK_l;
const int Keys::M = SDLK_m;
const int Keys::N = SDLK_n;
const int Keys::O = SDLK_o;
const int Keys::P = SDLK_p;
const int Keys::Q = SDLK_q;
const int Keys::R = SDLK_r;
const int Keys::S = SDLK_s;
const int Keys::T = SDLK_t;
const int Keys::U = SDLK_u;
const int Keys::V = SDLK_v;
const int Keys::W = SDLK_w;
const int Keys::X = SDLK_x;
const int Keys::Y = SDLK_y;
const int Keys::Z = SDLK_z;
const int Keys::LEFT_BRACKET = SDLK_LEFTBRACKET;
const int Keys::BACKSLASH = SDLK_BACKSLASH;
const int Keys::RIGHT_BRACKET = SDLK_RIGHTBRACKET;
const int Keys::GRAVE_ACCENT = SDLK_BACKQUOTE;
const int Keys::ESCAPE = SDLK_ESCAPE;
const int Keys::ENTER = SDLK_RETURN;
const int Keys::TAB = SDLK_TAB;
const int Keys::BACKSPACE = SDLK_BACKSPACE;
const int Keys::INSERT = SDLK_INSERT;
const int Keys::DEL = SDLK_DELETE;
const int Keys::RIGHT = SDLK_RIGHT;
const int Keys::LEFT = SDLK_LEFT;
const int Keys::DOWN = SDLK_DOWN;
const int Keys::UP = SDLK_UP;
const int Keys::PAGE_UP = SDLK_PAGEUP;
const int Keys::PAGE_DOWN = SDLK_PAGEDOWN;
const int Keys::HOME = SDLK_HOME;
const int Keys::END = SDLK_END;
const int Keys::CAPS_LOCK = SDLK_CAPSLOCK;
const int Keys::SCROLL_LOCK = SDLK_SCROLLLOCK;
const int Keys::NUM_LOCK = SDLK_NUMLOCKCLEAR;
const int Keys::PRINT_SCREEN = SDLK_PRINTSCREEN;
const int Keys::PAUSE = SDLK_PAUSE;
const int Keys::F1 = SDLK_F1;
const int Keys::F2 = SDLK_F2;
const int Keys::F3 = SDLK_F3;
const int Keys::F4 = SDLK_F4;
const int Keys::F5 = SDLK_F5;
const int Keys::F6 = SDLK_F6;
const int Keys::F7 = SDLK_F7;
const int Keys::F8 = SDLK_F8;
const int Keys::F9 = SDLK_F9;
const int Keys::F10 = SDLK_F10;
const int Keys::F11 = SDLK_F11;
const int Keys::F12 = SDLK_F12;
const int Keys::F13 = SDLK_F13;
const int Keys::F14 = SDLK_F14;
const int Keys::F15 = SDLK_F15;
const int Keys::F16 = SDLK_F16;
const int Keys::F17 = SDLK_F17;
const int Keys::F18 = SDLK_F18;
const int Keys::F19 = SDLK_F19;
const int Keys::F20 = SDLK_F20;
const int Keys::F21 = SDLK_F21;
const int Keys::F22 = SDLK_F22;
const int Keys::F23 = SDLK_F23;
const int Keys::F24 = SDLK_F24;
const int Keys::NumericKeypadZero = SDLK_KP_0;
const int Keys::NumericKeypadOne = SDLK_KP_1;
const int Keys::NumericKeypadTwo = SDLK_KP_2;
const int Keys::NumericKeypadThree = SDLK_KP_3;
const int Keys::NumericKeypadFour = SDLK_KP_4;
const int Keys::NumericKeypadFive = SDLK_KP_5;
const int Keys::NumericKeypadSix = SDLK_KP_6;
const int Keys::NumericKeypadSeven = SDLK_KP_7;
const int Keys::NumericKeypadEight = SDLK_KP_8;
const int Keys::NumericKeypadNine = SDLK_KP_9;
const int Keys::NumericKeypadDECIMAL = SDLK_KP_DECIMAL;
const int Keys::NumericKeypadDIVIDE = SDLK_KP_DIVIDE;
const int Keys::NumericKeypadMULTIPLY = SDLK_KP_MULTIPLY;
const int Keys::NumericKeypadSUBTRACT = SDLK_KP_MINUS;
const int Keys::NumericKeypadADD = SDLK_KP_PLUS;
const int Keys::NumericKeypadENTER = SDLK_KP_ENTER;
const int Keys::NumericKeypadEQUAL = SDLK_KP_EQUALS;
const int Keys::LEFT_SHIFT = SDLK_LSHIFT;
const int Keys::LEFT_CONTROL = SDLK_LCTRL;
const int Keys::LEFT_ALT = SDLK_LALT;
const int Keys::LEFT_SUPER = SDLK_LGUI;
const int Keys::RIGHT_SHIFT = SDLK_RSHIFT;
const int Keys::RIGHT_CONTROL = SDLK_RCTRL;
const int Keys::RIGHT_ALT = SDLK_RALT;
const int Keys::RIGHT_SUPER = SDLK_RGUI;
const int Keys::MENU = SDLK_MENU;

// const size_t Window::joystickCount = GLFW_JOYSTICK_LAST + 1;
// bool Window::joystickConnected[joystickCount];
// const char *Window::joystickName[joystickCount];
// int Window::joystickButtonsCount[joystickCount];
// const unsigned char *Window::joystickButtons[joystickCount];
// int Window::joystickAxesCount[joystickCount];
// const float *Window::joystickAxes[joystickCount];

} // namespace Blob::SDL2
