name: Linux gcc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gcc-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Install libs
      run: sudo apt-get install freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev libboost-all-dev gcc-11 g++-11
    - name: Configure
      run: cmake -H. -Bbuild -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11
    - name: Build
      run: cmake --build build --config Release
  gcc-default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Install libs
      run: sudo apt-get install freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev libboost-all-dev gcc g++
    - name: Configure
      run: cmake -H. -Bbuild -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
    - name: Build
      run: cmake --build build --config Release
